// <auto-generated />
using System;
using FastSchool.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FastSchool.Model.Migrations
{
    [DbContext(typeof(FastSchoolDBContext))]
    partial class FastSchoolDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FastSchool.Model.Commodity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("Code");

                    b.Property<string>("Consignee")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<int>("EnumExpressType");

                    b.Property<bool>("IsDelete");

                    b.Property<DateTime>("LastEitDateTime");

                    b.Property<string>("PickUpAddress")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("PickUpCode");

                    b.Property<decimal>("Ponus");

                    b.Property<string>("Remarks")
                        .HasMaxLength(80);

                    b.Property<string>("Sendaddress")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("State");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Commodity");
                });

            modelBuilder.Entity("FastSchool.Model.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("Code");

                    b.Property<Guid>("CommodityId");

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<bool>("IsDelete");

                    b.Property<DateTime>("LastEitDateTime");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("OrderState");

                    b.Property<Guid>("SendUserId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("SendUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("FastSchool.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("Code");

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<string>("FullName")
                        .HasMaxLength(15);

                    b.Property<bool>("IsDelete");

                    b.Property<DateTime>("LastEitDateTime");

                    b.Property<long>("Phone");

                    b.Property<long>("SchoolNumber");

                    b.Property<string>("UserName")
                        .HasMaxLength(15);

                    b.Property<string>("UserPwd")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FastSchool.Model.Commodity", b =>
                {
                    b.HasOne("FastSchool.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FastSchool.Model.Order", b =>
                {
                    b.HasOne("FastSchool.Model.Commodity", "Commodity")
                        .WithMany()
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FastSchool.Model.User", "SendUser")
                        .WithMany()
                        .HasForeignKey("SendUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FastSchool.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
